### ISSUE TITLE
AccessKey not valid

### ISSUE THREAD

**Issue by gbrueckl** [ProjectNami/ProjectNamiBlobCache#3]
Hi,

i am running Project Nami Wordpress together with BlobCache. All of my users get the following error message displayed at the very bottom of the page:
Fatal error: Uncaught exception 'RuntimeException' with message 'The provided account key '' is not a valid base64 string. It has to pass the check 'base64_decode(, true)'.' in D:\home\site\wwwroot\wp-content\plugins\project-nami-blob-cache\library\WindowsAzure\Common\Internal\StorageServiceSettings.php:185 Stack trace: #0 D:\home\site\wwwroot\wp-content\plugins\project-nami-blob-cache\library\WindowsAzure\Common\Internal\ServiceSettings.php(131): WindowsAzure\Common\Internal\StorageServiceSettings::WindowsAzure\Common\Internal{closure}('') #1 D:\home\site\wwwroot\wp-content\plugins\project-nami-blob-cache\library\WindowsAzure\Common\Internal\ServiceSettings.php(270): WindowsAzure\Common\Internal\StorageServiceSettings::WindowsAzure\Common\Internal{closure}(Array) #2 D:\home\site\wwwroot\wp-content\plugins\project-nami-blob-cache\library\WindowsAzure\Common\Internal\StorageServiceSettings.php(395): WindowsAzure\Common\Internal\ServiceSettings::matchedSpecification(Array, Object(Closure), Object(Closure in D:\home\site\wwwroot\wp-content\plugins\project-nami-blob-cache\library\WindowsAzure\Common\Internal\StorageServiceSettings.php on line 185

it is basically complaining about a missing Account Key (Azure Storage Account Key I would guess). However, I could not find any place where to specify it?!?

**Comment by patrickebates** [comment]
Have you created the app settings as listed in the ReadMe?
https://github.com/ProjectNami/ProjectNamiBlobCache/blob/master/ProjectNamiBlobCache/readme.md

**Comment by gbrueckl** [comment]
Hi,
thanks for the quick response!
no I did not, I followed the instructions from here:
https://github.com/ProjectNami/projectnami-blob-cache

**Comment by patrickebates** [comment]
Both pieces together are required for Blob Cache to operate.  The plugin handles writes, and the IIS Module checks for hits/misses and handles cache reads.

**Comment by patrickebates** [comment]
You may want to have a look at our ZIP package if you've not see it yet.  It contains all of the various components and more instructions on how they work together.
https://projectnami.blob.core.windows.net/cache/project-nami-blob-cache-3.0.1.zip

**Comment by gbrueckl** [comment]
ok, seems to work now! thanks!
one last question though: it says "Copy the contents of bin folder into your existing bin folder at the root of your site"
what would be the root-folder if the site is hosted as Azure Web Site?
site?
wwwroot?
the real root folder "\"`?

**Comment by patrickebates** [comment]
wwwroot, the root folder of the site itself.  so at the same level as your web.config will be.

**Comment by gbrueckl** [comment]
ok, thats what I assumed and did
then I restarted the Web App
for some reasons it is still not working and I get the following error messages:
[09-Jun-2016 12:41:26 UTC] Fail:
Code: 404
Value: The specified blob does not exist.
details (if any): .

if I browse a new sub-site, a new entry gets created in the blob-container which I specified for the plugin

any ideas?

**Comment by patrickebates** [comment]
If you're seeing files written to the storage container, then you must have StorageAccount, StorageKey, and StorageContainer configured correctly...

I would set Proactive to 0 and Debug to 1, if you haven't already.

Also, exactly where are you seeing this error?  In a log, or when attempting to access a page is the browser returning this data?

**Comment by gbrueckl** [comment]
just set Debug to 1, Proactive was already 0

the error appeared in the php_errors.log in the root of the FTP server of my Web App

for the root-web-site Debugging reveals:
!-- Key c5d5b508a448880ffaf946475b17e938 ServerVar https://mysite.azurewebsites.net/ Rewrite https://mysite.azurewebsites.net/index.php --

I can find the file c5d5b508a448880ffaf946475b17e938 in my blob cache folder

for all other sites it generates the new file in the cache folder but still says <Page loaded without caching>

**Comment by patrickebates** [comment]
To clarify, you're running multisite as subfolders?  I can't imagine that being an issue due to how the hashed filename is generated, but I believe we might have only tested the subdomain method of multisite.

**Comment by gbrueckl** [comment]
with root-web-site I mean index.php
its a single Web App which only hosts WordPress
